<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Force full width content layout
// add_filter( 'genesis_site_layout', '__genesis_return_full_width_content' );

add_action('genesis_after_header', 'genesischild_top_wrap_widgets');

//Removes Title and Description on Blog Archive
remove_action('genesis_before_loop', 'genesis_do_posts_page_heading');
remove_action('genesis_loop', 'genesis_do_loop');
add_action('genesis_loop', 'custom_entry_content'); // Add custom loop

function genesischild_top_wrap_widgets()
{
    $hero_url = get_the_post_thumbnail_url(get_the_ID(), 'full_hd');
    $posts_page = get_option('page_for_posts');
    $post_thumbnail_id = get_post_thumbnail_id($posts_page);
    $url = wp_get_attachment_image_src($post_thumbnail_id, 'full_hd');
    $hero = wp_get_attachment_image_url(get_post_thumbnail_id(get_option('page_for_posts')), 'full');
    $background_mobile = get_field('background_mobile', get_option('page_for_posts'));
    ?>

<section class="banner banner-single-post <?php echo (empty($hero)) ? 'empty' : null ?>">

        <div class="featured-img-hone">

            <?php /*if (!empty($background_mobile)): ?>
                <style>
                    @media screen and (max-width: 960px) {
                        .banner__rotate {
                            background-image: url(<?php echo $background_mobile ?>) !important;
                        }
                </style>
            <?php endif; */?>
			
			<img src="<?php echo $hero;?>">
			
		</div>

            <div class="banner__content">

                <h1 class="banner__title"><?php single_post_title() ?></h1>

                <?php if ($item2 = get_field('subtitle')): ?>
                    <h3><?php echo $item2 ?></h3>
                <?php endif; ?>
                <?php if ($link = get_field('contact_link')): ?>
                    <div class="button__container">
                        <a class="button button--tranperent" href="<?php echo $link['url']; ?>"
                           target="<?php if ($link['target']) {
                               echo $link['target'];
                           } else {
                               echo '_parent';
                           } ?>"><?php echo $link['title']; ?></a>
                    </div>
                <?php endif; ?>
				<?php if(get_field('title_excerpt')):?>
					<div class="title-text">
						<?php the_field('title_excerpt');?>
					</div>
				<?php endif;?>
            </div>
    </section>
    <div class="site-inner">
        <div class="grid-container">
            <div class="grid-x grid-margin-x list-decor">
                <?php get_template_part('parts/core/breadcrumbs', null); ?>

            </div>
        </div>
    </div>

<?php }

function custom_entry_content()
{ ?>
    <div id="main_container">
        <div class="default-page-container">
            <div class="grid-container">
                <div class="grid-x grid-margin-x list-decor">

                    <div class="cell">
                        <?php
                        $paged = get_query_var( 'paged' ) ? absint( get_query_var( 'paged' ) ) : 1;
                        $args = array(
                            'post_type' => 'post',
                            'post_status'    => 'publish',
                            'posts_per_page' => get_option('posts_per_page'),
                            'paged'          => $paged,
                        );

                        $id = get_the_ID();
                        global $wp_query;
                        $wp_query = new WP_Query( $args );
                        if ($wp_query -> have_posts()) :  ?>
                            <div class="faqs-list faqs-list-js">
                                <?php 	while ( $wp_query -> have_posts() ) :  $wp_query -> the_post();

                                    get_template_part( 'parts/news/news-item');
                                endwhile; ?>
                            </div>
                            <?php
                            the_posts_pagination( array(
                                'mid_size'  => 2,
                                'prev_text' => __( 'Previous Page', 'honelaw23' ),
                                'next_text' => __( 'Next Page', 'honelaw23' ),
                            ) );
                            remove_action( 'genesis_after_endwhile', 'genesis_posts_nav' );
                            do_action('genesis_after_endwhile'); ?>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php }

genesis();
?>
