<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Force full width content layout
// add_filter( 'genesis_site_layout', '__genesis_return_full_width_content' );

remove_action('genesis_loop', 'genesis_do_loop');
add_action('genesis_loop', 'custom_entry_content'); // Add custom loop
add_action('genesis_after_header', 'genesischild_top_wrap_widgets');

function genesischild_top_wrap_widgets()
{
    $hero_url = get_the_post_thumbnail_url(get_the_ID(), 'full_hd');
    $background_mobile = get_field('background_mobile', get_the_ID());
    ?>
    <section class="banner banner-single-post <?php echo (empty($hero_url)) ? 'empty' : null ?>">

        <div class="featured-img-hone">

            <?php /*if (!empty($background_mobile)): ?>
                <style>
                    @media screen and (max-width: 960px) {
                        .banner__rotate {
                            background-image: url(<?php echo $background_mobile ?>) !important;
                        }
                </style>
            <?php endif; */ ?>

            <img src="<?php echo $hero_url; ?>">

        </div>

        <div class="banner__content">

            <h1 class="banner__title"><?php the_title() ?></h1>

            <?php if ($item2 = get_field('subtitle')): ?>
                <h3><?php echo $item2 ?></h3>
            <?php endif; ?>
            <?php if ($link = get_field('contact_link')): ?>
                <div class="button__container">
                    <a class="button button--tranperent" href="<?php echo $link['url']; ?>"
                       target="<?php if ($link['target']) {
                           echo $link['target'];
                       } else {
                           echo '_parent';
                       } ?>"><?php echo $link['title']; ?></a>
                </div>
            <?php endif; ?>
            <?php if (get_field('title_excerpt')): ?>
                <div class="title-text">
                    <?php the_field('title_excerpt'); ?>
                </div>
            <?php endif; ?>
        </div>
        <div class="img-checkered"></div>
    </section>


<?php }

function custom_entry_content()
{ ?>
    <div id="main_container">
        <div class="default-page-container">

            <div class="grid-container">
                <div class="grid-x grid-margin-x list-decor">
                    <div class="cell">
                        <?php get_template_part('parts/core/breadcrumbs', null); ?>
                    </div>
                    <?php if (have_posts()) : ?>
                        <?php while (have_posts()) : the_post(); ?>
                            <div class="cell">
                                <?php add_filter('the_content', 'wpautop'); ?>
                                <?php the_content(); ?>
                            </div>
                        <?php endwhile; ?>
                    <?php endif; ?>
                </div>
                <? if (have_rows('faqs')): ?>
                    <div class="grid-x list-decor">
                        <div class="faqs-wrapper">
                            <?php if ($faq_section_heading = get_field('faq_section_heading')) : ?>
                                <div class="cell text-center faq__heading">
                                    <h2> <?php echo $faq_section_heading; ?></h2>
                                </div>
                            <?php endif; ?>
                            <div class="cell">

                                <div class="faqs-list">
                                    <?php while (have_rows('faqs')) : the_row(); ?>
                                        <article class="faq">
                                            <div class="faq__content">
                                                <?php if ($faq_title = get_sub_field('faq_title')) : ?>
                                                    <h2 class="faq__title"><?php echo $faq_title ?></h2>
                                                <?php endif; ?>
                                                <?php
                                                if ($faq_content = get_sub_field('faq_content')): ?>
                                                    <div class="faq__content more-4 more-style"><?php echo $faq_content ?></div>
                                                <?php endif; ?>
                                            </div>
                                            <?php if ($faq_thumbnail = get_sub_field('faq_thumbnail')) : ?>
                                                <?php echo wp_get_attachment_image($faq_thumbnail['id'], 'large', false, array('class' => 'faq__image')); ?>
                                            <?php endif; ?>
                                        </article>

                                    <?php endwhile; ?>
                                </div>


                            </div>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="grid-x grid-margin-x list-decor">
                    <?php if ($helpful_section_heading = get_field('helpful_section_heading')) : ?>
                        <div class="cell text-left helpful__heading">
                            <h2> <?php echo $helpful_section_heading; ?></h2>
                        </div>
                    <?php endif; ?>
                    <?php if (have_rows('helpful_links')) : ?>
                        <div class="cell helpful__links">
                            <?php while (have_rows('helpful_links')) : the_row() ?>
                                <?php if ($helpful_link = get_sub_field('helpful_link')) : ?>
                                    <a href="<?php echo $helpful_link['url'] ?>"
                                       target="<?php echo $helpful_link['target'] ?: '_self'; ?>" class="helpful__link">
                                        <?php echo $helpful_link['title']; ?>
                                    </a>
                                <?php endif; ?>
                            <?php endwhile ?>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
<?php }

genesis(); ?>