<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

// This file handles single entries, but only exists for the sake of child theme forward compatibility.
remove_action('genesis_loop', 'genesis_do_loop');
add_action('genesis_loop', 'custom_entry_content'); // Add custom loop
add_action('genesis_after_header', 'genesischild_top_wrap_widgets');

function genesischild_top_wrap_widgets()
{
    $hero_url = get_the_post_thumbnail_url(get_the_ID(), 'full_hd'); ?>
    <section class="banner banner-team">


        <?php if (get_field('mobile_image')): ?>


            <div class="banner__rotate bg-cover"
                 style="background-image: url(<?php echo $hero_url ?>);">
                <div class="banner__content">

                    <h1 class="banner__title"><?php the_title() ?></h1>
					
                    <?php if ($item2 = get_field('position')): ?>
                        <h3 class="banner__position"><?php echo $item2 ?></h3>
                    <?php endif; ?>
					<?php if (get_field('phone_number') || get_field('contact_link') || get_field('location') || get_field('practice_areas')):?>
					<div class="team-info">
						<?php if ($item3 = get_field('phone_number')): ?>
							<div class="team-phone-number"><a href="<?php echo esc_url( $item3['url'] ); ?>" target="<?php echo esc_attr( $item3['target'] ? $item3['target'] : '_self' ); ?>"><?php echo esc_html( $item3['title'] ); ?></a></div>
						<?php endif; ?>
						<?php if ($link = get_field('contact_link')): ?>
							<div class="button__container">
								<a class="button button--tranperent" href="<?php echo $link['url']; ?>"
								   target="<?php if ($link['target']) {
									   echo $link['target'];
								   } else {
									   echo '_parent';
								   } ?>"><?php echo $link['title']; ?></a>
							</div>
						<?php endif; ?>
						<?php if ($item4 = get_field('location')): ?>
							<div class="team-location"><a href="<?php echo esc_url( $item4['url'] ); ?>" target="<?php echo esc_attr( $item4['target'] ? $item4['target'] : '_self' ); ?>"><?php echo esc_html( $item4['title'] ); ?></a></div>
						<?php endif; ?>
						<?php if ($item5 = get_field('practice_areas')): ?>
							<div class="team-practice-areas"><?php the_field('practice_areas');?></div>
						<?php endif; ?>
					</div>
					<?php endif;?>
                </div>
            </div>

        <?php else: ?>

            <div class="banner__rotate bg-cover" style="background-image: url(<?php echo $hero_url ?>);">
                <div class="banner__content">

                    <h1 class="banner__title"><?php the_title() ?></h1>

                <?php if ($item2 = get_field('position')): ?>
                        <h3 class="banner__position"><?php echo $item2 ?></h3>
                    <?php endif; ?>
					<?php if (get_field('phone_number') || get_field('contact_link') || get_field('location') || get_field('practice_areas')):?>
					<div class="team-info">
						<?php if ($item3 = get_field('phone_number')): ?>
							<div class="team-phone-number"><a href="<?php echo esc_url( $item3['url'] ); ?>" target="<?php echo esc_attr( $item3['target'] ? $item3['target'] : '_self' ); ?>"><?php echo esc_html( $item3['title'] ); ?></a></div>
						<?php endif; ?>
						<?php if ($link = get_field('contact_link')): ?>
							<div class="button__container">
								<a class="team-contact" href="<?php echo $link['url']; ?>"
								   target="<?php if ($link['target']) {
									   echo $link['target'];
								   } else {
									   echo '_parent';
								   } ?>"><?php echo $link['title']; ?></a>
							</div>
						<?php endif; ?>
						<?php if ($item4 = get_field('location')): ?>
							<div class="team-location"><a href="<?php echo esc_url( $item4['url'] ); ?>" target="<?php echo esc_attr( $item4['target'] ? $item4['target'] : '_self' ); ?>"><?php echo esc_html( $item4['title'] ); ?></a></div>
						<?php endif; ?>
						<?php if ($item5 = get_field('practice_areas')): ?>
							<div class="team-practice-areas">
								<h4>Practice Areas</h4>
								<?php the_field('practice_areas');?>
							</div>
						<?php endif; ?>
						<?php if ($item6 = get_field('languages')): ?>
							<div class="team-languages">
								<h4>Languages</h4>
								<?php the_field('languages');?>
							</div>
						<?php endif; ?>
					</div>
					<?php endif;?>
                </div>
            </div>

        <?php endif; ?>
		
		<?php if (have_rows('logos')): ?>
			<section class="logos-part">
				<div class="grid-container">
					<div class="grid-x grid-margin-x align-center-middle award-slider">

						<?php while (have_rows('logos')): the_row();
							if ($image = get_sub_field('image')):?>
								<div class="award-wrapper">
								<?php if ($link = get_sub_field('link')): ?>
									<a href="<?php echo $link; ?>" target="_blank" class="cell large-2 medium-3 small-6  grid-x align-center">
								<?php endif; ?>

								<img src="<?php echo $image['url']; ?>" alt="  <?php echo $image['alt']; ?>"
									 class="logos-part__image">

								<?php if ($link): ?>
									</a>
								<?php endif; ?>
								</div>
							<?php endif;
						endwhile; ?>
					</div>
				</div>
			</section>
		<?php endif; ?>

    </section>

<?php }

function custom_entry_content()
{ ?>

    <div id="main_container" class="post-about-us">

        <div class="default-post-container">
	        
            <?php if (have_rows('tabs')): ?>
                <section class="team-tab">
                    <div class="grid-container">
                        <div class="grid-x grid-margin-x">
                            <div class="cell">
                                <?php get_template_part('parts/core/breadcrumbs', null); ?>
                            </div>
                            <div class="cell">
                                <ul class="team-tab-list">
                                    <?php
                                    $i = 1;
                                    while (have_rows('tabs')): the_row();
                                        $title = get_sub_field('tab_name') ? get_sub_field('tab_name') : 'Tab-' . $i; ?>
                                        <li class="team-tab-li <?php if ($i == '1') {
                                            echo 'open';
                                        } ?>" data-tab-id="team-tab-id-<?php echo $i; ?>"><?php echo $title ?></li>
                                        <?php $i++; endwhile; ?>
                                </ul>
                                <?php
                                $i = 1;
                                while (have_rows('tabs')): the_row();
                                    $content = get_sub_field('content'); ?>
                                    <div class="team-tab-content list-decor team-tab-id-<?php echo $i; ?> <?php if ($i == '1') {
                                        echo 'open';
                                    } ?>">
                                        <?php echo $content ?>
                                    </div>
                                    <?php $i++; endwhile; ?>
                            </div>
                        </div>
                    </div>
                </section>
            <?php endif; ?>


        </div>
    </div>
<?php }

genesis();
?>
